"""answers use question_key instead of question_id

Revision ID: dcedc56e34cb
Revises: 02f0eaf71b3d
Create Date: 2026-09-20 11:44:41.351292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcedc56e34cb'
down_revision: Union[str, None] = '02f0eaf71b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('question_key', sa.String(), nullable=False))
    op.drop_constraint('answers_user_id_question_id_key', 'answers', type_='unique')
    op.create_unique_constraint(None, 'answers', ['user_id', 'question_key'])
    op.drop_constraint('answers_question_id_fkey', 'answers', type_='foreignkey')
    op.drop_column('answers', 'question_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('answers_question_id_fkey', 'answers', 'questions', ['question_id'], ['id'])
    op.drop_constraint(None, 'answers', type_='unique')
    op.create_unique_constraint('answers_user_id_question_id_key', 'answers', ['user_id', 'question_id'])
    op.drop_column('answers', 'question_key')
    # ### end Alembic commands ###
