"""add mutual_at and feedback_requested flags to matches

Revision ID: f5ebe6446928
Revises: c0c5282c1375
Create Date: 2026-09-20 14:09:06.102511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5ebe6446928'
down_revision: Union[str, None] = 'c0c5282c1375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('mutual_at', sa.DateTime(), nullable=True))
    op.add_column('matches', sa.Column('feedback_requested_a', sa.Boolean(), nullable=False))
    op.add_column('matches', sa.Column('feedback_requested_b', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'feedback_requested_b')
    op.drop_column('matches', 'feedback_requested_a')
    op.drop_column('matches', 'mutual_at')
    # ### end Alembic commands ###
